.TH "controllers Directory Reference" 3 "droneProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
controllers Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdroneRobot\&.py\fP"
.br
.ti -1c
.RI "file \fBTrain_PPO\&.py\fP"
.br
.ti -1c
.RI "file \fBTrain_SAC\&.py\fP"
.br
.ti -1c
.RI "file \fBTrain_TDP\&.py\fP"
.br
.in -1c
