.TH "Train_PPO" 3 "droneProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Train_PPO
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBppo_path\fP = os\&.path\&.join('Training', 'Saved Models', f'Drone_PPO_Model_{datetime\&.datetime\&.now()\&.strftime('%Y_%m_%d_%H_%M_%S')}')"
.br
.ti -1c
.RI "\fBlog_path\fP = os\&.path\&.join('Training', 'Logs')"
.br
.ti -1c
.RI "int \fBepisodes\fP = 100"
.br
.ti -1c
.RI "\fBenv\fP = \fBDroneRobot\fP()"
.br
.ti -1c
.RI "\fBdebugMode\fP"
.br
.ti -1c
.RI "int \fBtimesteps\fP = env\&.steps_per_episode * \fBepisodes\fP"
.br
.ti -1c
.RI "\fBmodel\fP = PPO('MlpPolicy', \fBenv\fP, verbose=1, tensorboard_log=\fBlog_path\fP, device='cpu', ent_coef=10, learning_rate=0\&.0001)"
.br
.ti -1c
.RI "\fBtotal_timesteps\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "Train_PPO\&.debugMode"

.PP
Definition at line \fB17\fP of file \fBTrain_PPO\&.py\fP\&.
.SS "Train_PPO\&.env = \fBDroneRobot\fP()"

.PP
Definition at line \fB16\fP of file \fBTrain_PPO\&.py\fP\&.
.SS "int Train_PPO\&.episodes = 100"

.PP
Definition at line \fB13\fP of file \fBTrain_PPO\&.py\fP\&.
.SS "Train_PPO\&.log_path = os\&.path\&.join('Training', 'Logs')"

.PP
Definition at line \fB10\fP of file \fBTrain_PPO\&.py\fP\&.
.SS "Train_PPO\&.model = PPO('MlpPolicy', \fBenv\fP, verbose=1, tensorboard_log=\fBlog_path\fP, device='cpu', ent_coef=10, learning_rate=0\&.0001)"

.PP
Definition at line \fB27\fP of file \fBTrain_PPO\&.py\fP\&.
.SS "Train_PPO\&.ppo_path = os\&.path\&.join('Training', 'Saved Models', f'Drone_PPO_Model_{datetime\&.datetime\&.now()\&.strftime('%Y_%m_%d_%H_%M_%S')}')"

.PP
Definition at line \fB8\fP of file \fBTrain_PPO\&.py\fP\&.
.SS "int Train_PPO\&.timesteps = env\&.steps_per_episode * \fBepisodes\fP"

.PP
Definition at line \fB21\fP of file \fBTrain_PPO\&.py\fP\&.
.SS "Train_PPO\&.total_timesteps"

.PP
Definition at line \fB36\fP of file \fBTrain_PPO\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for droneProject from the source code\&.
